/// Generated by AssetsRefGenerator on 2022/10/15
class Res {
  static const String bg = "assets/images/bg.jpg";
  static const String bg2 = "assets/images/bg2.jpg";
  static const String logo = "assets/images/logo.png";
}
