/// Generated by AssetsRefGenerator on 2022/10/24
class Res {
  static const String ads = "assets/images/ads.png";
  static const String bg = "assets/images/bg.jpg";
  static const String complaint = "assets/images/complaint.png";
  static const String contract = "assets/images/contract.png";
  static const String dashboard = "assets/images/dashboard.png";
  static const String events = "assets/images/events.png";
  static const String external_services = "assets/images/external_services.png";
  static const String logo = "assets/images/logo.png";
  static const String maintenance = "assets/images/maintenance.png";
  static const String man = "assets/images/man.png";
  static const String panic = "assets/images/panic.png";
  static const String payment = "assets/images/payment.png";
  static const String phone_book = "assets/images/phone_book.png";
  static const String violation = "assets/images/violation.png";
  static const String visitors = "assets/images/visitors.png";
}
